const INTERACTIVE_ROLES = new Set([
  "button",
  "link",
  "checkbox",
  "radio",
  "switch",
  "tab",
  "menuitem",
  "menuitemradio",
  "option",
  "combobox",
  "textbox",
  "searchbox",
  "spinbutton",
]);

const MAX_LABEL_LENGTH = 240;

function textOf(node) {
  return [node.name, node.text, node.value]
    .find((value) => typeof value === "string" && value.trim())
    ?.trim()
    .slice(0, MAX_LABEL_LENGTH) ?? "";
}

function flattenSnapshot(nodes, result = []) {
  for (const node of nodes ?? []) {
    if (node && typeof node === "object") {
      result.push(node);
      flattenSnapshot(node.children, result);
    }
  }
  return result;
}

function isEditable(node) {
  return ["textbox", "searchbox", "spinbutton"].includes(node.role) ||
    (node.role === "combobox" && node.editable !== false);
}

function addCandidate(target, candidate) {
  if (!target.has(candidate.id)) target.set(candidate.id, candidate);
  const current = target.get(candidate.id);
  if (!current.operations.includes(candidate.operation)) {
    current.operations.push(candidate.operation);
  }
}

/**
 * Convert the JSON accessibility snapshot returned by playwright-cli into a
 * closed action space. IDs are the CLI's current observation refs, never
 * selectors generated by Jev.
 */
export function buildActionSpace(snapshot, { maxCandidates = 120 } = {}) {
  const candidates = new Map();
  const nodes = flattenSnapshot(snapshot);

  for (const node of nodes) {
    if (!node.ref || !INTERACTIVE_ROLES.has(node.role)) continue;
    const label = textOf(node) || node.role;
    const base = {
      id: node.ref,
      ref: node.ref,
      role: node.role,
      label,
      value: typeof node.value === "string" ? node.value : "",
      checked: node.checked,
      selected: node.selected,
      expanded: node.expanded,
      operations: [],
    };

    if (["checkbox", "switch", "radio"].includes(node.role)) {
      addCandidate(candidates, {
        ...base,
        operation: node.checked === true || node.checked === "true" ? "UNCHECK" : "CHECK",
      });
    } else if (isEditable(node)) {
      addCandidate(candidates, { ...base, operation: "TYPE_TEXT" });
      addCandidate(candidates, { ...base, operation: "CLICK" });
    } else {
      addCandidate(candidates, { ...base, operation: "CLICK" });
    }
  }

  const ordered = [...candidates.values()].slice(0, maxCandidates);
  const byOperation = Object.fromEntries([
    "CLICK",
    "TYPE_TEXT",
    "CHECK",
    "UNCHECK",
  ].map((operation) => [
    operation,
    ordered
      .filter((candidate) => candidate.operations.includes(operation))
      .map((candidate) => ({ ...candidate, operation })),
  ]));

  const controls = [
    { id: "SCROLL_DOWN", operation: "SCROLL_DOWN", label: "Scroll down" },
    { id: "SCROLL_UP", operation: "SCROLL_UP", label: "Scroll up" },
    { id: "WAIT", operation: "WAIT", label: "Wait for the page to update" },
    { id: "DONE", operation: "DONE", label: "All requirements are visibly satisfied" },
    { id: "BLOCKED", operation: "BLOCKED", label: "No supported operation can make progress" },
  ];

  return {
    candidates: ordered,
    byOperation,
    controls,
    omitted: Math.max(0, candidates.size - ordered.length),
  };
}

export function candidateById(actionSpace, id, operation) {
  const candidate = actionSpace.candidates.find((item) => item.id === id && (!operation || item.operations.includes(operation)));
  return (candidate && operation) ? { ...candidate, operation } : candidate ??
    actionSpace.controls.find((control) => control.id === id) ?? null;
}

export function summarizeActionSpace(actionSpace) {
  return actionSpace.candidates.map(({ id, ref, role, label, value, checked, selected, expanded, operations }) => ({
    id,
    ref,
    role,
    label,
    value,
    checked,
    selected,
    expanded,
    operations,
  }));
}

export function operationForCandidate(candidate) {
  return candidate?.operation ?? candidate?.operations?.[0] ?? candidate?.id;
}
